import { ResumeData, TemplateConfig } from './types';

export const INITIAL_RESUME: ResumeData = {
  id: 'default',
  title: 'My Resume',
  header: {
    fullName: 'Alex J. Developer',
    headline: 'Senior Frontend Engineer',
    email: 'alex@example.com',
    phone: '(555) 123-4567',
    location: 'San Francisco, CA',
    website: 'alexdev.com',
    linkedin: 'linkedin.com/in/alexdev',
    github: 'github.com/alexdev',
  },
  summary: 'Creative and detail-oriented Frontend Engineer with 5+ years of experience building scalable web applications. Expert in **React**, **TypeScript**, and UI/UX design. Passionate about performance optimization and accessible design.',
  experience: [
    {
      id: 'exp-1',
      company: 'TechFlow Solutions',
      location: 'San Francisco, CA',
      roles: [
        {
          id: 'role-1',
          title: 'Senior Frontend Engineer',
          startDate: '2021-03',
          endDate: '',
          current: true,
          description: '- Led the migration of a legacy monolithic app to a modern micro-frontend architecture using **React** and **Webpack Module Federation**.\n- Improved site performance by **40%** through code splitting, lazy loading, and image optimization.\n- Mentored 3 junior developers and established code quality standards.',
        },
      ],
    },
    {
      id: 'exp-2',
      company: 'WebSphere Inc.',
      location: 'Austin, TX',
      roles: [
        {
          id: 'role-2',
          title: 'Frontend Developer',
          startDate: '2018-06',
          endDate: '2021-02',
          current: false,
          description: '- Developed responsive user interfaces for a SaaS analytics platform serving 10k+ daily users.\n- Collaborated with designers to implement a new design system using **Tailwind CSS**.',
        },
      ],
    },
  ],
  education: [
    {
      id: 'edu-1',
      school: 'University of Texas at Austin',
      degree: 'Bachelor of Science',
      field: 'Computer Science',
      location: 'Austin, TX',
      startDate: '2014-08',
      endDate: '2018-05',
      notes: 'Graduated Cum Laude. Dean\'s List 2016-2018.',
    },
  ],
  skills: [
    {
      id: 'skill-1',
      name: 'Frontend',
      items: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS', 'Redux'],
    },
    {
      id: 'skill-2',
      name: 'Backend & Tools',
      items: ['Node.js', 'GraphQL', 'PostgreSQL', 'Docker', 'Git'],
    },
  ],
  projects: [
    {
      id: 'proj-1',
      name: 'EcoTrack',
      link: 'ecotrack.io',
      description: 'An open-source carbon footprint tracker built with React Native and Firebase.',
    },
  ],
};

export const TEMPLATES: TemplateConfig[] = [
  {
    id: 'ats-classic',
    name: 'ATS Classic',
    thumbnail: 'https://picsum.photos/200/300?grayscale',
    isATS: true,
    tags: ['ATS', 'Minimal', 'Clean'],
    layout: 'single-column',
    fontHeadings: 'font-serif',
    fontBody: 'font-serif',
    colors: { primary: 'text-gray-900', secondary: 'text-gray-700', text: 'text-black', bg: 'bg-white' },
  },
  {
    id: 'modern-sans',
    name: 'Modern Sans',
    thumbnail: 'https://picsum.photos/200/300',
    isATS: false,
    tags: ['Modern', 'Clean'],
    layout: 'single-column',
    fontHeadings: 'font-sans font-bold',
    fontBody: 'font-sans',
    colors: { primary: 'text-blue-700', secondary: 'text-gray-600', text: 'text-gray-800', bg: 'bg-white' },
  },
  {
    id: 'sidebar-left',
    name: 'Executive Sidebar',
    thumbnail: 'https://picsum.photos/200/300',
    isATS: false,
    tags: ['Creative', '2-Column'],
    layout: 'two-column-left',
    fontHeadings: 'font-sans font-bold tracking-tight',
    fontBody: 'font-sans',
    colors: { primary: 'text-slate-800', secondary: 'text-slate-500', text: 'text-slate-700', bg: 'bg-white' },
  },
  {
    id: 'sidebar-right',
    name: 'Creative Right',
    thumbnail: 'https://picsum.photos/200/300',
    isATS: false,
    tags: ['Creative', '2-Column'],
    layout: 'two-column-right',
    fontHeadings: 'font-serif font-bold',
    fontBody: 'font-sans',
    colors: { primary: 'text-emerald-700', secondary: 'text-emerald-600', text: 'text-gray-800', bg: 'bg-stone-50' },
  },
  // Add more to reach 8 conceptually, for now 4 distinct structural ones cover the reqs for demo
  {
    id: 'modern-sidebar',
    name: 'Modern Sidebar',
    thumbnail: 'https://picsum.photos/seed/modern/200/300',
    isATS: false,
    tags: ['Modern', 'Sidebar', 'Visual'],
    layout: 'modern-sidebar',
    fontHeadings: 'font-sans font-bold tracking-tight uppercase',
    fontBody: 'font-sans',
    colors: { primary: 'text-slate-900', secondary: 'text-slate-500', text: 'text-slate-700', bg: 'bg-white' },
  },
  {
    id: 'ats-modern',
    name: 'ATS Modern',
    thumbnail: 'https://picsum.photos/200/300?blur',
    isATS: true,
    tags: ['ATS', 'Modern'],
    layout: 'single-column',
    fontHeadings: 'font-sans font-semibold uppercase',
    fontBody: 'font-sans',
    colors: { primary: 'text-black', secondary: 'text-gray-800', text: 'text-black', bg: 'bg-white' },
  },
  {
    id: 'minimal-mono',
    name: 'Minimal Mono',
    thumbnail: 'https://picsum.photos/200/300',
    isATS: false,
    tags: ['Minimal', 'Mono'],
    layout: 'single-column',
    fontHeadings: 'font-mono font-bold',
    fontBody: 'font-mono text-sm',
    colors: { primary: 'text-black', secondary: 'text-gray-600', text: 'text-gray-800', bg: 'bg-white' },
  },
  {
    id: 'bold-header',
    name: 'Bold Header',
    thumbnail: 'https://picsum.photos/200/300',
    isATS: false,
    tags: ['Creative', 'Bold'],
    layout: 'single-column',
    fontHeadings: 'font-sans font-black text-3xl',
    fontBody: 'font-sans',
    colors: { primary: 'text-indigo-900', secondary: 'text-indigo-600', text: 'text-slate-800', bg: 'bg-white' },
  },
  {
    id: 'compact-ats',
    name: 'ATS Dense',
    thumbnail: 'https://picsum.photos/200/300',
    isATS: true,
    tags: ['ATS', 'Compact'],
    layout: 'single-column',
    fontHeadings: 'font-serif font-bold border-b border-black',
    fontBody: 'font-serif text-sm',
    colors: { primary: 'text-black', secondary: 'text-black', text: 'text-black', bg: 'bg-white' },
  },
];
